version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 207567760300.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t simple-docker-service-0affdb118e49 .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging and pushing the Docker image...
      - docker tag simple-docker-service-0affdb118e49:latest 207567760300.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-0affdb118e49:latest
      - docker push 207567760300.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-0affdb118e49:latest

artifacts:
  files:
    - '**/*'